version: '3.1'
 
services:
  nextcloud:
    image: nextcloud
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    restart: always
 
volumes:
  nextcloud_data: